export const FORMATIONS = [
  {
    cat: "bur",
    top: "linear-gradient(90deg,#2563EB,#4F46E5)",
    title: "Microsoft Office Expert",
    desc: "Word, Excel, PowerPoint et Outlook au niveau professionnel. Certification Microsoft.",
    dur: "40h",
    lvl: "Tous niveaux",
    fmt: "Dr. Haddad Nabil",
    prix: "25 000",
    mode: "Presentiel / En ligne",
  },
  {
    cat: "bur",
    top: "linear-gradient(90deg,#0EA5E9,#2563EB)",
    title: "Excel Avance & Business Intelligence",
    desc: "TCD, Power Query, macros VBA et dashboards professionnels.",
    dur: "30h",
    lvl: "Intermediaire",
    fmt: "Mme Kaci Lynda",
    prix: "30 000",
    mode: "Presentiel",
  },
  {
    cat: "bur",
    top: "linear-gradient(90deg,#10B981,#0EA5E9)",
    title: "Saisie & Frappe Rapide",
    desc: "Vitesse de frappe, saisie de donnees et competences secretariat.",
    dur: "20h",
    lvl: "Debutant",
    fmt: "Mme Bouzid Fatima",
    prix: "15 000",
    mode: "Presentiel",
  },
  {
    cat: "dev",
    top: "linear-gradient(90deg,#8B5CF6,#4F46E5)",
    title: "Developpement Web Full Stack",
    desc: "HTML, CSS, JavaScript, React.js et Node.js - de zero au dev full stack.",
    dur: "120h",
    lvl: "Debutant",
    fmt: "M. Benmoussa Yacine",
    prix: "65 000",
    mode: "Presentiel / En ligne",
  },
  {
    cat: "dev",
    top: "linear-gradient(90deg,#4F46E5,#8B5CF6)",
    title: "Python & Data Science",
    desc: "Programmation Python, Pandas, visualisation et intro au Machine Learning.",
    dur: "80h",
    lvl: "Debutant / Intermediaire",
    fmt: "Dr. Rais Sofiane",
    prix: "55 000",
    mode: "En ligne",
  },
  {
    cat: "cyb",
    top: "linear-gradient(90deg,#EF4444,#F59E0B)",
    title: "Cybersecurite Fondamentaux",
    desc: "Protection des systemes, reseaux securises, gestion des incidents et conformite.",
    dur: "60h",
    lvl: "Intermediaire",
    fmt: "M. Meziane Adel",
    prix: "70 000",
    mode: "Presentiel",
  },
  {
    cat: "cyb",
    top: "linear-gradient(90deg,#DC2626,#EF4444)",
    title: "Ethical Hacking & Pentest",
    desc: "Tests d'intrusion, audit de securite et rapports professionnels.",
    dur: "80h",
    lvl: "Avance",
    fmt: "M. Meziane Adel",
    prix: "90 000",
    mode: "Presentiel",
  },
  {
    cat: "ges",
    top: "linear-gradient(90deg,#10B981,#0EA5E9)",
    title: "Gestion Documentaire & Archives",
    desc: "Normes d'archivage, plan de classement, numerisation et GED.",
    dur: "35h",
    lvl: "Tous niveaux",
    fmt: "Mme Belhadj Samira",
    prix: "35 000",
    mode: "Presentiel",
  },
  {
    cat: "ges",
    top: "linear-gradient(90deg,#10B981,#4F46E5)",
    title: "Management de Projet",
    desc: "Methodes agiles et traditionnelles, MS Project, planification.",
    dur: "45h",
    lvl: "Intermediaire",
    fmt: "Dr. Ouali Mounir",
    prix: "45 000",
    mode: "Presentiel / En ligne",
  },
];

export const CAT_LBL = {
  bur: "Bureautique",
  dev: "Developpement",
  cyb: "Cybersecurite",
  ges: "Gestion",
};

export const CAT_CLS = {
  bur: { bg: "var(--blue-bg)", col: "var(--blue)" },
  dev: { bg: "var(--violet-bg)", col: "var(--violet)" },
  cyb: { bg: "var(--red-bg)", col: "var(--red)" },
  ges: { bg: "var(--green-bg)", col: "var(--green)" },
};

export const FORMATION_CATEGORY_OPTIONS = [
  { value: "bur", label: "Bureautique" },
  { value: "dev", label: "Developpement" },
  { value: "cyb", label: "Cybersecurite" },
  { value: "ges", label: "Gestion" },
];

export const FORMATION_LEVEL_OPTIONS = [
  "Debutant",
  "Intermediaire",
  "Avance",
  "Tous niveaux",
  "Debutant / Intermediaire",
];

export const FORMATION_MODE_OPTIONS = [
  "Presentiel",
  "En ligne",
  "Presentiel / En ligne",
];

export const PARTNERS = [
  "Sonatrach",
  "Algerie Telecom",
  "BNA",
  "Sonelgaz",
  "Air Algerie",
  "CNEP-Banque",
  "Ministere de l'Education",
  "Universite d'Alger",
  "CNAS",
  "Saidal",
  "APC Blida",
];

export const SERVICES = [
  {
    id: "s1",
    label: "Archivage Physique",
    icon: "fa-box-archive",
    iconCls: "var(--blue-bg)",
    iconCol: "var(--blue)",
    kpis: [
      { n: "10K+", l: "m2 stockage" },
      { n: "ISO", l: "Certifie" },
      { n: "24/7", l: "Surveillance" },
    ],
    title: "Archivage Physique Professionnel",
    body: "Notre service d'archivage physique propose une solution complete pour la prise en charge, le transport, le classement et la conservation de vos documents d'entreprise.",
    feats: [
      "Collecte et transport securise de vos archives",
      "Tri, classement et inventaire complet",
      "Stockage en entrepots climatises et securises",
      "Systeme de tracabilite et suivi en ligne",
      "Recuperation rapide sur demande en 24h",
      "Destruction securisee certifiee",
      "Rapport d'inventaire mensuel detaille",
    ],
  },
  {
    id: "s2",
    label: "Numerisation",
    icon: "fa-scanner-image",
    iconCls: "rgba(14,165,233,.1)",
    iconCol: "var(--cyan)",
    kpis: [
      { n: "600dpi", l: "Resolution" },
      { n: "OCR", l: "AR/FR/EN" },
      { n: "99.9%", l: "Precision" },
    ],
    title: "Vos archives digitalisees",
    body: "Transformez vos documents papier en actifs numeriques exploitables grace a nos technologies de scan et d'OCR multilingue de pointe.",
    feats: [
      "Scan haute resolution jusqu'a 600 DPI",
      "OCR multilingue (Arabe, Francais, Anglais)",
      "Indexation automatique et manuelle",
      "Export en PDF/A, TIFF, JPEG, Word",
      "Controle qualite image par image",
      "Metadonnees et classification automatique",
      "Livraison sur cle USB, disque dur ou cloud",
    ],
  },
  {
    id: "s3",
    label: "Archivage Numerique",
    icon: "fa-cloud-arrow-up",
    iconCls: "var(--amber-bg)",
    iconCol: "var(--amber)",
    kpis: [
      { n: "AES", l: "256-bit" },
      { n: "99.9%", l: "Uptime" },
      { n: "3x", l: "Backup" },
    ],
    title: "Toujours disponible, toujours securise",
    body: "Notre solution cloud garantit la securite, la perennite et l'accessibilite de vos documents depuis n'importe quel appareil.",
    feats: [
      "Hebergement en Algerie sur serveurs certifies",
      "Chiffrement AES-256 bit de toutes les donnees",
      "Sauvegardes automatiques triple redondance",
      "Acces web et application mobile",
      "Gestion des droits d'acces par utilisateur",
      "Historique des acces et audit trail",
      "SLA 99.9% de disponibilite garantie",
    ],
  },
  {
    id: "s4",
    label: "GED",
    icon: "fa-diagram-project",
    iconCls: "var(--green-bg)",
    iconCol: "var(--green)",
    kpis: [
      { n: "100%", l: "Sans papier" },
      { n: "API", l: "Integrations" },
      { n: "eSign", l: "Certifiee" },
    ],
    title: "Automatisez vos flux documentaires",
    body: "Notre solution GED vous permet de dematerialiser, organiser et faire circuler vos documents de facon intelligente.",
    feats: [
      "Workflows de validation configurables sans code",
      "Gestion des versions de documents",
      "Signatures electroniques certifiees",
      "Recherche full-text dans le contenu",
      "Integration ERP via API REST",
      "Tableaux de bord et statistiques avancees",
      "Notifications et alertes automatiques",
    ],
  },
  {
    id: "s5",
    label: "Confidentialite",
    icon: "fa-shield-halved",
    iconCls: "var(--violet-bg)",
    iconCol: "var(--violet)",
    kpis: [
      { n: "NDA", l: "Systematique" },
      { n: "ISO", l: "27001" },
      { n: "Loi", l: "18-07" },
    ],
    title: "Vos donnees 100% protegees",
    body: "La confidentialite de vos informations est notre priorite absolue. Protocoles conformes aux reglementations algeriennes et internationales.",
    feats: [
      "Acces biometrique aux locaux de stockage",
      "Videosurveillance 24h/24 - 7j/7",
      "Accord de confidentialite NDA systematique",
      "Personnel habilite et certifie",
      "Chiffrement bout-en-bout de toutes communications",
      "Destruction certifiee conforme RGPD / Loi 18-07",
      "Audit de securite annuel par tiers certifie",
    ],
  },
];

export const LOGICIELS = [
  {
    title: "SmartCourrier",
    ico: "fa-envelope-open-text",
    grad: "linear-gradient(135deg,#2563EB,#4F46E5)",
    desc: "Gestion complete du courrier entrant, sortant et interne pour administrations et entreprises.",
    feats: [
      "Enregistrement et numerotation automatique",
      "Circuit de validation configurable",
      "Suivi et tracabilite complete",
      "Interface bilingue AR/FR",
    ],
    price: "120 000 DA",
    priceSub: "/ an - licence",
    priceType: "paid",
  },
  {
    title: "SmartArchives",
    ico: "fa-boxes-stacked",
    grad: "linear-gradient(135deg,#10B981,#0EA5E9)",
    desc: "Gestion des archives physiques et numeriques avec recherche intelligente et QR codes.",
    feats: [
      "Plan de classement personnalisable",
      "QR code et codes-barres",
      "Recherche full-text et metadonnees",
      "Module de numerisation integre",
    ],
    price: "180 000 DA",
    priceSub: "/ an - licence",
    priceType: "paid",
  },
  {
    title: "SmartBiblio",
    ico: "fa-book-open",
    grad: "linear-gradient(135deg,#8B5CF6,#4F46E5)",
    desc: "Systeme de gestion de bibliotheque et centre de documentation pour etablissements.",
    feats: [
      "Catalogage MARC21 / Dublin Core",
      "Gestion des prets et retours",
      "OPAC - Catalogue en ligne",
      "Statistiques de frequentation",
    ],
    price: "90 000 DA",
    priceSub: "/ an - licence",
    priceType: "paid",
  },
  {
    title: "SmartGED",
    ico: "fa-diagram-project",
    grad: "linear-gradient(135deg,#F59E0B,#EF4444)",
    desc: "Plateforme GED collaborative avec workflows, signatures electroniques et versioning.",
    feats: [
      "Workflows sans code configurables",
      "Signature electronique certifiee",
      "Collaboration en temps reel",
      "API REST pour integrations",
    ],
    price: "Sur devis",
    priceSub: "Selon volume & utilisateurs",
    priceType: "contact",
  },
  {
    title: "SmartLearn",
    ico: "fa-graduation-cap",
    grad: "linear-gradient(135deg,#0EA5E9,#8B5CF6)",
    desc: "LMS complet pour la gestion des formations en ligne et presentiel avec certificats.",
    feats: [
      "Catalogue de formations en ligne",
      "Suivi de progression apprenants",
      "Certificats numeriques automatiques",
      "Dashboard formateur avance",
    ],
    price: "15 000 DA",
    priceSub: "/ mois - SaaS",
    priceType: "paid",
  },
  {
    title: "SmartContracts",
    ico: "fa-file-contract",
    grad: "linear-gradient(135deg,#10B981,#F59E0B)",
    desc: "Gestion du cycle de vie des contrats : creation, negociation, signature et suivi.",
    feats: [
      "Modeles de contrats personnalisables",
      "Alertes d'echeance automatiques",
      "Signature electronique avancee",
      "Archivage automatique",
    ],
    price: "Sur devis",
    priceSub: "Selon besoins",
    priceType: "contact",
  },
];
